import { app } from './core.js';
import { icon } from './icons.js';

const topicDefinitions = [
  ['Assumption', 'Find the unstated idea the argument needs.'],
  ['Strengthen', 'Choose information that makes the conclusion more likely.'],
  ['Weaken', 'Choose information that damages the conclusion or its support.'],
  ['Paradox / Explain', 'Resolve facts that seem inconsistent.'],
  ['Inference', 'Identify what must or most reasonably follows from the facts.'],
  ['Conclusion', 'Identify the claim the author is trying to establish.'],
  ['Main Point', 'State the passage\'s central message or purpose.'],
  ['Flaw', 'Describe the error in the argument\'s reasoning.'],
  ['Evaluate', 'Find the information that would best test the argument.'],
  ['Complete the Passage', 'Complete the reasoning in a way that fits its logic.'],
  ['Parallel Reasoning', 'Match the structure or flaw of another argument.'],
  ['Conditional / Deductive Logic', 'Apply rules, conditions, or formal constraints.'],
  ['Principle', 'Select or apply a general rule that supports the judgment.'],
  ['Method / Point at Issue', 'Describe an argumentative method or a disagreement.'],
  ['Role / Function', 'Explain what a statement does within the argument.'],
  ['Argument Structure', 'Map how evidence, intermediate claims, and conclusions connect.'],
  ['Interpretation', 'Determine what a statement or result means in context.'],
  ['Plan / Decision', 'Assess a proposed action, prediction, or practical choice.'],
  ['Other', 'Covers uncommon or ambiguous formats that do not fit reliably elsewhere.']
];

const helpLinks = [
  ['help-start', 'Quick start'],
  ['help-navigation', 'Navigation & theme'],
  ['help-dashboard', 'Dashboard'],
  ['help-tests', 'CAT Tests'],
  ['help-focused', 'Focused Practice'],
  ['help-solving', 'Solving questions'],
  ['help-results', 'Session analysis'],
  ['help-review', 'Review Queue'],
  ['help-solutions', 'Solutions'],
  ['help-errors', 'Error Log'],
  ['help-reports', 'Reports & exports'],
  ['help-data', 'Data & privacy'],
  ['help-topics', 'Question types'],
  ['help-access', 'Mobile & accessibility'],
  ['help-trouble', 'Troubleshooting']
];

function helpSection(id, kicker, title, body, tone = 'teal') {
  return `<section class="help-section card" id="${id}" data-help-section data-tone="${tone}"><span class="section-kicker">${kicker}</span><h2>${title}</h2>${body}</section>`;
}

function helpView() {
  return `<div class="help-hero"><div><span class="eyebrow">CR LAB HANDBOOK</span><h1>How to use the application</h1><p>Everything from your first practice set to reviewing mistakes, reading solutions, and moving progress to another device.</p></div><div class="help-hero-mark">${icon('book')}</div></div>
  <div class="help-search card"><label for="help-search"><strong>Find an answer</strong><span class="tiny muted">Search features, buttons, timers, scores, or data.</span></label><div class="help-search-field">${icon('spark')}<input class="input" id="help-search" type="search" placeholder="Try: timer, clear response, backup..." autocomplete="off"><button class="btn small" data-action="clear-help-search" hidden>Clear</button></div><p class="tiny muted" id="help-search-status" role="status" aria-live="polite">Showing the complete guide.</p></div>
  <div class="help-layout">
    <aside class="help-toc card" aria-label="Help topics"><strong>On this page</strong>${helpLinks.map(([id, label]) => `<button data-help-target="${id}">${label}</button>`).join('')}</aside>
    <div class="help-content">
      ${helpSection('help-start', 'START HERE', 'Quick start', `<ol class="help-steps"><li><strong>Choose a route.</strong> Use <b>CAT Tests</b> for original timed sets or <b>Focused Practice</b> for a custom mix.</li><li><strong>Solve and navigate.</strong> Select an option, then use Next, Previous, or the question navigator. Leaving a selected question submits and locks it.</li><li><strong>Finish and analyze.</strong> End the session to see accuracy, timing, topic results, and every question.</li><li><strong>Review deliberately.</strong> Use the Error Log, Solutions, and Review Queue to learn from weak areas.</li><li><strong>Protect your work.</strong> Download a JSON backup from Reports, especially before changing devices or clearing browser data.</li></ol><div class="help-callout good"><strong>A useful first session</strong><span>Start with a 10-question Balanced random mix. Your results will give the weaker-skills strategy and dashboard enough evidence to become useful.</span></div>`, 'teal')}
      ${helpSection('help-navigation', 'GLOBAL CONTROLS', 'Navigation and appearance', `<div class="help-grid"><div><h3>Main navigation</h3><p>The top bar opens Dashboard, CAT Tests, Focused Practice, Review Queue, Solutions, Error Log, Reports, and this Help page. On smaller screens, swipe the navigation row horizontally to see every item.</p></div><div><h3>Quick Practice / Resume</h3><p><b>Quick Practice</b> opens Focused Practice when no session exists. If a session is saved, the same button becomes <b>Resume</b>.</p></div><div><h3>Light, Dark, Auto</h3><p>Light and Dark force that appearance. Auto follows your device setting. The choice is saved separately, so clearing study progress does not reset the theme.</p></div><div><h3>One active session</h3><p>Only one unfinished practice can exist at a time. Resume it or discard it before starting another set.</p></div></div>`, 'violet')}
      ${helpSection('help-dashboard', 'HOME', 'Dashboard', `<div class="help-grid"><div><h3>Practice routes</h3><p><b>Test your timing</b> opens CAT Tests, <b>Sharpen a skill</b> opens Focused Practice, and <b>Revisit & retain</b> opens the Review Queue.</p></div><div><h3>Your next focus</h3><p>After you have scored attempts, the banner points to your lowest-accuracy topic. Before that, it recommends a starting mix.</p></div><div><h3>Progress cards</h3><p>Questions attempted counts answered questions. Overall accuracy uses answered questions with a usable key. Average time uses answered questions. Open errors counts Error Log items not marked Reviewed.</p></div><div><h3>Charts and recent sessions</h3><p>The 7-day chart uses active local dates; a gap means no scored answers. Topic accuracy lists weaker topics first. Recent sessions provides a fast Analyze button.</p></div></div><div class="help-callout warn"><strong>Remove all progress</strong><span>The red button opens a confirmation dialog. It permanently removes sessions, answers, timers, notes, errors, review history, and the active session from this browser. Download a backup first.</span></div>`, 'coral')}
      ${helpSection('help-tests', 'FULL-SET MODE', 'CAT Tests', `<p>CAT Tests preserves the question order and available section timing from the source bank. A card shows its question count, sections, and total available time.</p><ul><li><b>Start set</b> or a section button starts only that section.</li><li><b>Full set</b> combines every listed section in order and uses a separate countdown for each timed section.</li><li>When a section expires, the current selected response is submitted and the app advances to the next section. On the final section, the session finishes.</li><li>Original source identifiers remain internally attached to questions so keys and saved history stay stable, even though the interface presents one CAT library.</li></ul>`, 'teal')}
      ${helpSection('help-focused', 'CUSTOM MODE', 'Focused Practice', `<div class="help-grid"><div><h3>Question count</h3><p>Choose 1 to 50 questions. The final size cannot exceed the number available in the selected topics.</p></div><div><h3>Topic cards</h3><p>Select one or several question types. With none selected, the complete bank is eligible. The count on each card is the number of available questions in that category.</p></div><div><h3>Balanced random mix</h3><p>Shuffles eligible questions, then rotates across selected topics as evenly as availability allows. It prefers questions you have not answered before when enough are available.</p></div><div><h3>Focus on weaker skills</h3><p>Uses your completed, keyed answers to give lower-accuracy topics more places in the mix. New or lightly attempted topics receive smoothing so one answer does not dominate. Without history, it behaves like a balanced mix.</p></div></div><p class="tiny muted">Both strategies may reuse previously answered questions when the unattempted pool is too small for the requested set.</p>`, 'coral')}
      ${helpSection('help-solving', 'ACTIVE SESSION', 'Solving questions and using the timer', `<div class="help-lifecycle"><div><span>1</span><strong>Select</strong><p>Your choice is provisional. You may change it or use Clear response while you remain on that question.</p></div><div><span>2</span><strong>Submit</strong><p>Next, Previous, a different navigator number, Finish, or Check answer submits a selected choice.</p></div><div><span>3</span><strong>Lock</strong><p>Submission stops that question's timer and permanently locks the choice for this session.</p></div><div><span>4</span><strong>Review</strong><p>Check answer reveals the keyed answer and explanation immediately. Reviewing a locked answer adds no question time.</p></div></div><ul><li><b>Leaving blank:</b> moving away without a selection keeps the question unanswered; its active time is retained and continues if you return.</li><li><b>Clear response:</b> removes only a provisional selection. It is unavailable after submission.</li><li><b>Flag:</b> marks a question for attention. Flags appear underlined in the navigator and enter the later review workflow.</li><li><b>Question timer:</b> focused practice records active time per question. It stops on submission and while paused or away from practice.</li><li><b>Section countdown:</b> timed CAT sets show remaining section time. Reviewing a submitted question freezes the countdown until you move to an unanswered question.</li><li><b>Pause:</b> freezes question and section timing. Resume continues from the stored remaining time; it does not restart.</li><li><b>Leaving the practice page:</b> automatically pauses the session. Dashboard time and time while the app is closed are not charged.</li><li><b>Navigator:</b> green means answered and locked; an underline means flagged. Next unanswered and Next flagged wrap through the set.</li><li><b>End & Review:</b> asks for confirmation, submits a current selection if present, then scores and saves the session.</li></ul><div class="help-callout"><strong>Important answer rule</strong><span>A click alone is not final. A selected option becomes final when you leave the question or press Check answer. After that it cannot be changed.</span></div>`, 'gold')}
      ${helpSection('help-results', 'AFTER PRACTICE', 'Session analysis', `<p>Session analysis appears immediately after completion and remains available through Analyze in Dashboard or Reports.</p><div class="help-grid"><div><h3>Score</h3><p>Correct keyed answers divided by all questions that have usable answer keys. Skips therefore lower the test-style score.</p></div><div><h3>Accuracy</h3><p>Correct answers divided only by answered questions with usable keys. Unanswered and unkeyed questions are excluded.</p></div><div><h3>Filters</h3><p>Show all, incorrect, unanswered, flagged, correct, or not-scored questions. Pagination keeps long reviews contained.</p></div><div><h3>View solution</h3><p>Opens the exact question, your choice, source key, reasoning method, option analysis, takeaway, and editorial confidence information.</p></div></div><p><b>Review mistakes</b> opens the Error Log scoped to that session. <b>Dashboard</b> returns home.</p>`, 'violet')}
      ${helpSection('help-review', 'RETAIN', 'Review Queue and spaced repetition', `<p>Incorrect, skipped, and flagged questions enter one deduplicated recall queue. A later mistake makes an existing item due again.</p><ol><li>Choose Due now, Upcoming, or All scheduled.</li><li>Open <b>Recall question</b> or <b>Review early</b>.</li><li>Answer from memory and explain the logical link to yourself.</li><li>Press <b>Reveal solution</b>. Your recall choice then locks, but it does not alter the original test answer or score.</li><li>Rate the recall: <b>Again</b> (10 minutes), <b>Hard</b> (1 day), <b>Good</b> (3 days), or <b>Easy</b> (7 days). Successful later intervals grow, up to one year.</li></ol><p>The Due, Upcoming, and Unique questions cards describe the current schedule. A device-clock warning prevents a review from being recorded before a future-dated saved event.</p>`, 'gold')}
      ${helpSection('help-solutions', 'LEARN', 'Solutions library and explanation labels', `<p>Search by question content, ID, topic, or source issue. Filter the bank by editorial status, then open any item for its solution.</p><dl class="help-definitions"><div><dt>AI-reviewed</dt><dd>An individually written explanation passed a separate AI review. This is not human expert verification.</dd></div><div><dt>Human expert reviewed</dt><dd>A named human approval exists in the item's review history.</dd></div><div><dt>Needs review</dt><dd>An authored explanation has a highlighted source-wording, calculation, or answer-key concern. The source key remains unchanged.</dd></div><div><dt>Automated draft</dt><dd>Guidance generated from passage extracts and topic templates. Treat it as unverified and inspect the question yourself.</dd></div><div><dt>Source key unavailable</dt><dd>No usable answer key exists, so the question is not scored.</dd></div></dl><p><b>Practice reviewed questions</b> starts a shuffled set of up to 10 questions whose explanations are AI-reviewed or human-expert reviewed and match the current filters.</p>`, 'teal')}
      ${helpSection('help-errors', 'DIAGNOSE', 'Error Log', `<p>The Error Log is created automatically when a completed session contains an incorrect, skipped, or flagged question.</p><ul><li><b>Search</b> matches question text, topic, source details, and saved notes.</li><li><b>Review status</b> filters Open, Reviewed, or All items.</li><li><b>Reason</b> filters Incorrect, Skipped, or Flagged items.</li><li><b>Read question</b> expands the original prompt without leaving the list.</li><li><b>Your reasoning and lesson</b> is a private note field. Press Save note to persist it.</li><li><b>Mark reviewed</b> changes organizational status only; it does not create a spaced-repetition rating. Reopen reverses the status.</li><li><b>View solution</b> opens the full question analysis. Session-scoped reviews offer Show all sessions to remove the scope.</li></ul>`, 'coral')}
      ${helpSection('help-reports', 'MEASURE', 'Reports, history, and exports', `<div class="help-grid"><div><h3>Daily accuracy</h3><p>Shows the last 14 dates on which you recorded scored answers, using your device's local date.</p></div><div><h3>Topic performance</h3><p>Attempts, scored answers, correct answers, accuracy, and average answer time are grouped by topic.</p></div><div><h3>Session history</h3><p>Every completed session remains analyzable. The list is paginated after 10 rows.</p></div><div><h3>Download Excel report</h3><p>Creates Sessions, Question Log, Topic Summary, Error Log, Review History, and Review Schedule worksheets.</p></div></div><div class="help-callout good"><strong>JSON vs Excel</strong><span>Use JSON Backup/Restore to preserve or transfer live application data, including a paused active session. Use Excel for analysis outside the app; Excel cannot be restored into the app.</span></div>`, 'violet')}
      ${helpSection('help-data', 'LOCAL-FIRST', 'Data, privacy, backup, and reset', `<ul><li><b>No account or authentication:</b> the app does not identify users and does not sync to a server.</li><li><b>Where data lives:</b> progress belongs to this browser profile and this exact site origin. Another browser, private window, domain, or device has separate data.</li><li><b>Move to another device:</b> download Backup JSON on the old device, open Reports on the new device, and choose Restore JSON. Imports merge by record ID and keep existing records.</li><li><b>Active session backup:</b> the backup stores it paused at the export instant. It restores only when the destination has no active session and no completed copy with the same ID.</li><li><b>Browser storage warning:</b> keep the tab open and download a backup. The app may be holding unsaved progress only in memory.</li><li><b>Clear progress:</b> Dashboard → Remove all progress → confirm the red warning. The theme preference remains.</li></ul><div class="help-callout warn"><strong>Before sharing or clearing a browser</strong><span>Anyone using the same browser profile and site address shares that local progress. Use a separate browser profile for separation, and back up before deleting site data.</span></div>`, 'gold')}
      ${helpSection('help-topics', 'REFERENCE', 'Question types and topic families', `<p>Topics are inferred from question-stem patterns because the source PDF does not provide a complete taxonomy. Ambiguous formats remain under Other. Topic families group related skills for navigation and reporting.</p><div class="help-topic-list">${topicDefinitions.map(([topic, definition]) => `<div><strong>${topic}</strong><span>${definition}</span></div>`).join('')}</div>`, 'teal')}
      ${helpSection('help-access', 'EVERY DEVICE', 'Mobile, scrolling, pagination, and accessibility', `<ul><li>On phones, the main navigation scrolls horizontally. Question content and the navigator have their own bounded scroll areas so controls remain reachable.</li><li>Long Tests, Topics, Solutions, Error Log, Reviews, result questions, and session history use pagination. First/Last jump to an endpoint; arrow buttons move one page.</li><li>Changing pages returns that list to its top instead of moving the whole application unpredictably.</li><li>Keyboard users can Tab through controls. Focus outlines show the active control, dialogs trap focus, and Escape closes reset or solution dialogs.</li><li>Status is communicated with text and shapes as well as color. Light and dark themes retain the same meanings.</li><li>Reduced-motion device settings minimize completion, chart, scrolling, and hover movement.</li></ul>`, 'violet')}
      ${helpSection('help-trouble', 'COMMON QUESTIONS', 'Troubleshooting', `<details open><summary>Why did my answer become unchangeable?</summary><p>You navigated away, pressed Check answer, or finished the session. Those actions submit the selected option, stop its timer, and lock it by design.</p></details><details><summary>Why is a question still unanswered?</summary><p>You left it without selecting an option. Time already spent is retained, but no answer is recorded until you select and submit one.</p></details><details><summary>Why did the timer appear frozen?</summary><p>Timers stop while paused, outside practice, or reviewing a locked response. A section countdown resumes when you move to an unanswered question.</p></details><details><summary>Why is topic performance empty?</summary><p>Complete a session with answered questions that have usable answer keys. Provisional choices and unfinished sessions are not part of historical reports.</p></details><details><summary>Why does my other device show no progress?</summary><p>There is no account sync. Transfer a JSON backup or use separate local histories.</p></details><details><summary>Why is an explanation marked Automated draft or Needs review?</summary><p>The label states its actual editorial confidence. Automated drafts are not individually verified; Needs review identifies a known concern without silently altering the source key.</p></details><details><summary>Why can\'t I start another session?</summary><p>An unfinished session already exists. Use Resume, or Discard it after confirming. Completed sessions and notes are not removed by Discard.</p></details><details><summary>Why does opening index.html directly fail?</summary><p>The app uses browser modules and must be served over HTTP. GitHub Pages works normally. For local use, run npm start and open http://127.0.0.1:4173.</p></details>`, 'coral')}
      <div class="empty help-no-results" hidden>No help sections match that search. Try a shorter term such as “timer”, “score”, “backup”, or “solution”.</div>
    </div>
  </div>`;
}

function bindHelp() {
  if (!document.getElementById('help-search')) return;
  const input = document.getElementById('help-search'), clear = app.querySelector('[data-action="clear-help-search"]'), status = document.getElementById('help-search-status'), empty = app.querySelector('.help-no-results');
  const filter = () => {
    const query = input.value.trim().toLowerCase();
    const sections = [...app.querySelectorAll('[data-help-section]')];
    let visible = 0;
    sections.forEach(section => { const match = !query || section.textContent.toLowerCase().includes(query); section.hidden = !match; if (match) visible++; });
    clear.hidden = !query; empty.hidden = visible !== 0;
    status.textContent = query ? `${visible} of ${sections.length} guide sections match “${input.value.trim()}”.` : 'Showing the complete guide.';
    app.querySelectorAll('[data-help-target]').forEach(button => { button.hidden = !!query && document.getElementById(button.dataset.helpTarget)?.hidden; });
  };
  input.oninput = filter;
  clear.onclick = () => { input.value = ''; filter(); input.focus(); };
  app.querySelectorAll('[data-help-target]').forEach(button => button.onclick = () => {
    const target = document.getElementById(button.dataset.helpTarget); if (!target || target.hidden) return;
    target.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'start' });
    target.setAttribute('tabindex', '-1'); target.focus({ preventScroll: true });
  });
}

export { topicDefinitions, helpLinks, helpSection, helpView, bindHelp };
