// solutions-ui — one responsibility, with explicit module dependencies.
import { state, qById, esc, displayTestTitle } from './core.js';
import { store } from './storage.js';

function solutionHTML(q, attempt) {
  const x = q.explanation, selected = attempt?.selected, correct = selected && x.keyed ? selected === q.answer : null;
  const status = !selected ? 'Unanswered' : !x.keyed ? 'Not scored' : x.reviewStatus === 'needs-review' ? correct ? 'Matches source key' : 'Differs from source key' : correct ? 'Correct' : 'Incorrect';
  const authored = !!x.editorial, verified = x.reviewStatus === 'expert-reviewed';
  const disclaimer = authored
    ? verified ? 'This question-specific solution has a named human expert approval in its review history. It is independent editorial analysis, not an official source explanation.'
      : 'This solution was written individually for this question using AI-assisted reasoning. Its review history is shown below; AI review is not human expert verification. Check any highlighted source issue before relying on the key.'
    : 'The answer key comes from the source PDF. The guidance below is an automated, unverified draft using passage extracts and topic-based templates—not an expert-written solution. It may misidentify the argument or miss why an option succeeds or fails.';
  const editorial = authored ? `<div class="editorial-meta"><span>Author: ${esc(x.editorial.author)} · Version ${x.editorial.version} · ${esc(x.editorial.authoredAt)}</span>${x.issue ? `<p class="editorial-issue" role="note"><strong>Needs review:</strong> ${esc(x.issue)}</p>` : ''}<details data-details-key="editorial-${esc(q.id)}"><summary>Editorial review history</summary>${x.editorial.reviews.length ? x.editorial.reviews.map(review => `<p><strong>${esc(review.reviewer)}</strong> · ${esc(review.kind)} · ${esc(review.reviewedAt)} · ${esc(review.verdict)}<br>${esc(review.notes)}</p>`).join('') : '<p>No independent review recorded yet.</p>'}</details></div>` : '';
  const audit = (x.choiceAnalysis || []).map(item => `<div class="choice-audit-row ${item.correct ? 'correct' : ''}"><span class="choice-audit-letter">${esc(item.label)}</span><span><strong>${item.correct ? 'Source-keyed option. ' : ''}</strong>${esc(item.reason)}</span></div>`).join('');
  return `<div class="solution-panel ${correct === false ? 'incorrect' : ''}"><div class="solution-title"><span>Answer review · ${esc(q.type)}</span><span class="${correct === true ? 'good' : correct === false ? 'bad' : 'warn'}">${status}</span></div><div class="row between wrap"><div class="solution-answer"><strong>${esc(x.answer)}</strong>${x.answerText ? ` — ${esc(x.answerText)}` : ''}</div><span class="confidence-badge ${x.keyed ? '' : 'unkeyed'}">${esc(x.confidence)}</span></div><div class="solution-disclaimer">${esc(disclaimer)}</div>${editorial}${x.editorial?.pitfalls ? `<div class="solution-step solution-reasoning"><strong>Watch for this trap</strong>${esc(x.editorial.pitfalls)}</div>` : ''}<div class="argument-map"><div class="argument-node evidence solution-reasoning"><strong>${authored ? 'Passage in brief' : 'Extracted passage context'}</strong>${esc(x.evidence)}</div><div class="argument-node claim solution-reasoning"><strong>${authored ? 'Claim / question target' : 'Possible claim / result'}</strong>${esc(x.conclusion)}</div></div><div class="solution-grid"><div class="solution-step solution-reasoning"><strong>Study approach</strong>${esc(x.method)}</div><div class="solution-step solution-reasoning"><strong>${authored ? x.issue ? 'Analysis of the disputed source key' : 'Why the source-keyed answer works' : 'Draft analysis of the source key'}</strong>${esc(x.why)}</div></div>${audit ? `<details class="choice-audit" data-details-key="options-${esc(q.id)}"><summary>Review every option</summary><div class="choice-audit-list" data-scroll-key="options-${esc(q.id)}" tabindex="0" role="region" aria-label="Answer option review">${audit}</div></details>` : ''}<div class="solution-step solution-reasoning" style="margin-top:10px"><strong>Practice takeaway</strong>${esc(x.takeaway)}</div></div>`
}

function analysisModal() { const ref = state.analysis; if (!ref) return ''; const sessions = store().sessions || [], s = sessions.find(x => x.id === ref.sessionId) || (state._result?.id === ref.sessionId ? state._result : null), q = qById.get(ref.qid), a = s?.answers?.[ref.qid]; if (!q) return ''; return `<div class="modal analysis-modal" role="dialog" aria-modal="true" aria-labelledby="analysis-title"><div class="modal-card" data-scroll-key="analysis-${esc(q.id)}"><div class="row between modal-header"><div><strong id="analysis-title">Question ${q.number} analysis</strong><div class="tiny muted">${esc(q.family)} · ${esc(q.type)} · ${esc(displayTestTitle(q.corpus, q.test, q.section))}</div></div><button class="btn small" data-action="close-analysis">Close</button></div><div class="q-stem">${esc(q.prompt)}</div><div>${q.choices.map(c => `<div class="choice ${c.label === q.answer ? 'selected' : ''}"><span class="letter">${c.label}</span><span>${esc(c.text)}${c.label === a?.selected ? ' <span class="tiny muted">· Your answer</span>' : ''}</span></div>`).join('')}</div>${solutionHTML(q, a)}</div></div>` }

export { solutionHTML, analysisModal };
